kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: JAVA_TRUSTSTORE_OPTIONS
      value: "-Djavax.net.ssl.trustStore=$(NAV_TRUSTSTORE_PATH)
              -Djavax.net.ssl.trustStorePassword=$(NAV_TRUSTSTORE_PASSWORD)"
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MaxRAMPercentage=75
              -Djavax.net.ssl.keyStore=$(NAV_TRUSTSTORE_PATH)
              -Djavax.net.ssl.keyStorePassword=$(NAV_TRUSTSTORE_PASSWORD)
              -Djavax.net.ssl.keyStoreType=jks
              --enable-preview
              $(JAVA_PROXY_OPTIONS) $(JAVA_TRUSTSTORE_OPTIONS)"
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{ this }}
           {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  webproxy: true
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 10m
      memory: 1024Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true